import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Eterna sidebar (autogenerated from docs/eterna/)
  eternaSidebar: [
    {type: 'autogenerated', dirName: 'eterna'}
  ],
  
  // Silk sidebar (autogenerated from docs/silk/)
  silkSidebar: [
    {type: 'autogenerated', dirName: 'silk'}
  ],
};

export default sidebars;